// Code generated by ogen, DO NOT EDIT.
package order_v1

type OrdersOrderUUIDCancelPostRes interface {
	ordersOrderUUIDCancelPostRes()
}

type OrdersOrderUUIDGetRes interface {
	ordersOrderUUIDGetRes()
}

type OrdersOrderUUIDPayPostRes interface {
	ordersOrderUUIDPayPostRes()
}

type OrdersPostRes interface {
	ordersPostRes()
}
