// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// OrdersOrderUUIDCancelPostParams is parameters of POST /orders/{order_uuid}/cancel operation.
type OrdersOrderUUIDCancelPostParams struct {
	// UUID заказа.
	OrderUUID uuid.UUID
}

func unpackOrdersOrderUUIDCancelPostParams(packed middleware.Parameters) (params OrdersOrderUUIDCancelPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeOrdersOrderUUIDCancelPostParams(args [1]string, argsEscaped bool, r *http.Request) (params OrdersOrderUUIDCancelPostParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrdersOrderUUIDGetParams is parameters of GET /orders/{order_uuid} operation.
type OrdersOrderUUIDGetParams struct {
	// UUID заказа.
	OrderUUID uuid.UUID
}

func unpackOrdersOrderUUIDGetParams(packed middleware.Parameters) (params OrdersOrderUUIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeOrdersOrderUUIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params OrdersOrderUUIDGetParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrdersOrderUUIDPayPostParams is parameters of POST /orders/{order_uuid}/pay operation.
type OrdersOrderUUIDPayPostParams struct {
	// UUID заказа.
	OrderUUID uuid.UUID
}

func unpackOrdersOrderUUIDPayPostParams(packed middleware.Parameters) (params OrdersOrderUUIDPayPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeOrdersOrderUUIDPayPostParams(args [1]string, argsEscaped bool, r *http.Request) (params OrdersOrderUUIDPayPostParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
