// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	OrdersOrderUUIDCancelPostOperation OperationName = "OrdersOrderUUIDCancelPost"
	OrdersOrderUUIDGetOperation        OperationName = "OrdersOrderUUIDGet"
	OrdersOrderUUIDPayPostOperation    OperationName = "OrdersOrderUUIDPayPost"
	OrdersPostOperation                OperationName = "OrdersPost"
)
