// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// OrdersOrderUUIDCancelPost implements POST /orders/{order_uuid}/cancel operation.
//
// Отменяет заказ, если он ещё не оплачен.
//
// POST /orders/{order_uuid}/cancel
func (UnimplementedHandler) OrdersOrderUUIDCancelPost(ctx context.Context, params OrdersOrderUUIDCancelPostParams) (r OrdersOrderUUIDCancelPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrdersOrderUUIDGet implements GET /orders/{order_uuid} operation.
//
// Возвращает информацию о заказе по его UUID.
//
// GET /orders/{order_uuid}
func (UnimplementedHandler) OrdersOrderUUIDGet(ctx context.Context, params OrdersOrderUUIDGetParams) (r OrdersOrderUUIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrdersOrderUUIDPayPost implements POST /orders/{order_uuid}/pay operation.
//
// Проводит оплату ранее созданного заказа.
//
// POST /orders/{order_uuid}/pay
func (UnimplementedHandler) OrdersOrderUUIDPayPost(ctx context.Context, req *PayOrderRequest, params OrdersOrderUUIDPayPostParams) (r OrdersOrderUUIDPayPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrdersPost implements POST /orders operation.
//
// Создаёт новый заказ на основе выбранных
// пользователем деталей.
//
// POST /orders
func (UnimplementedHandler) OrdersPost(ctx context.Context, req *CreateOrderRequest) (r OrdersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
