// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// OrdersOrderUUIDCancelPost implements POST /orders/{order_uuid}/cancel operation.
	//
	// Отменяет заказ, если он ещё не оплачен.
	//
	// POST /orders/{order_uuid}/cancel
	OrdersOrderUUIDCancelPost(ctx context.Context, params OrdersOrderUUIDCancelPostParams) (OrdersOrderUUIDCancelPostRes, error)
	// OrdersOrderUUIDGet implements GET /orders/{order_uuid} operation.
	//
	// Возвращает информацию о заказе по его UUID.
	//
	// GET /orders/{order_uuid}
	OrdersOrderUUIDGet(ctx context.Context, params OrdersOrderUUIDGetParams) (OrdersOrderUUIDGetRes, error)
	// OrdersOrderUUIDPayPost implements POST /orders/{order_uuid}/pay operation.
	//
	// Проводит оплату ранее созданного заказа.
	//
	// POST /orders/{order_uuid}/pay
	OrdersOrderUUIDPayPost(ctx context.Context, req *PayOrderRequest, params OrdersOrderUUIDPayPostParams) (OrdersOrderUUIDPayPostRes, error)
	// OrdersPost implements POST /orders operation.
	//
	// Создаёт новый заказ на основе выбранных
	// пользователем деталей.
	//
	// POST /orders
	OrdersPost(ctx context.Context, req *CreateOrderRequest) (OrdersPostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
